### ISSUE TITLE
Parameter expansion error

### ISSUE THREAD

**Issue by dismantl** [jheretic/commotion-build#2]
When running a build, I get an error indicating a problem with shell parameter expansion:
`WARNING: No feed for package '{commotion,commotion-gui}' found, maybe it's already part of the standard packages?`

I am running GNU bash 4.2.50(1)-release, cmake 3.0.2

**Comment by dismantl** [comment]
gettext (GNU gettext-runtime) 0.18.1

**Comment by jheretic** [comment]
Resolved with 9551a98
